CREATE DATABASE	QuanLyCuaHangXe
ON PRIMARY 
(
	NAME = 'QLCHX_DATA',
	FILENAME='D:\DataBase_QuanLyCuaHangXe\QLCHX_DATA.MDF',
	SIZE = 10,
	MAXSIZE = 100,
	FILEGROWTH = 1
)
LOG ON
(
	NAME = 'QLCHX_LOG',
	FILENAME='D:\DataBase_QuanLyCuaHangXe\QLCHX_LOG.LDF',
	SIZE = 10,
	MAXSIZE = 100,
	FILEGROWTH = 1
)
CREATE TABLE LoaiXe
(
	MALOAI NVARCHAR(20) NOT NULL
	CONSTRAINT PK_LoaiXe
	PRIMARY KEY(MALOAI),
	TENLOAIXE NVARCHAR(30) NOT NULL,
	HANGSX NVARCHAR(50) NOT NULL,
	SOLUONG INT,
	DUNGTICH INT,
	TOCDOTOIDA INT,
	DONGIA FLOAT
)

CREATE TABLE XeMay
(
	MAXE NVARCHAR(50) NOT NULL
	CONSTRAINT pk_XeMay
	primary key(MAXE),
	MALOAI NVARCHAR(20) NOT NULL,
	CONSTRAINT fk_MaLoai
	FOREIGN KEY(MALOAI)
	REFERENCES LoaiXe(MALOAI)
	ON DELETE CASCADE ON UPDATE CASCADE,
	SOKHUNG INT NOT NULL,
	SOMAY INT NOT NULL,
	MAUXE NVARCHAR(20) NULL,
	DONGIA FLOAT NULL
)
INSERT INTO [dbo].[XeMay]([MAXE],[TENXE],[NHASX],[SOLUONG],[THONGTINBAOHANH],[DONVITINH],[MOTA])
VALUES('X01','Ablade','HonDa',10,N'Bảo Hành 12 Tháng',N'Chiếc',N'Xe Mới')

CREATE TABLE NhanVien
(
	MANHANVIEN NVARCHAR(50) NOT NULL,
	CONSTRAINT pk_NhanVien
	PRIMARY KEY(MANHANVIEN),
	TENNHANVIEN NVARCHAR(50) NOT NULL,
	GIOITINH NVARCHAR(10) NOT NULL,
	SODT INT NOT NULL,
	SOCMND NVARCHAR(20) NOT NULL,
	NAMSINH NVARCHAR(30) NOT NULL,
	NGAYVAO NVARCHAR(30) NOT NULL,
	CHUCVU NVARCHAR(30) NOT NULL,
	DIACHI NVARCHAR(30) NOT NULL,
	LUONG FLOAT
)
INSERT INTO [dbo].[NhanVien]([MANHANVIEN],[TENNHANVIEN],[GIOITINH],[SODT],[SOCMND],[NAMSINH],[NGAYVAO],[CHUCVU],[DIACHI],[LUONG])
VALUES('NV01',N'Hùng','Nam',0854926311,197391890,'25/04/2000','20/06/2020',N'Nhân Viên',N'799 Nguyễn Kiệm',2000000)

SELECT * FROM [dbo].[NhanVien]

CREATE PROC select_NV
as
	SELECT * FROM [dbo].[NhanVien]

EXEC select_NV


CREATE TABLE KhachHang
(
	MAKHACHHANG NVARCHAR(50) NOT NULL
	CONSTRAINT pk_KhachHang
	PRIMARY KEY(MAKHACHHANG),
	TENKHACHHANG NVARCHAR(50) NOT NULL,
	GIOITINH CHAR(10) NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	DIENTHOAI INT NULL,
	EMAIL NVARCHAR(50) NULL
)


INSERT INTO [dbo].[KhachHang]([MAKHACHHANG],[TENKHACHHANG],[GIOITINH],[DIACHI],[DIENTHOAI],[EMAIL])
VALUES ('KH01',N'Nguyễn Hùng','Nam',N'799 Nguyễn Kiệm',0854926311,'Vanhung2504@gmail')

CREATE PROC select_KH
as
	SELECT * FROM [dbo].[KhachHang]

EXEC select_KH

CREATE PROC delete_KH @makh nvarchar(50)
AS
	DELETE FROM [dbo].[KhachHang] WHERE [MAKHACHHANG] = @makh
EXEC delete_KH KH02

CREATE TABLE NhaCungCap
(
	MANHACUNGCAP NVARCHAR(50) NOT NULL
	CONSTRAINT pk_NhaCungCap
	primary KEY(MANHACUNGCAP),
	TENNHACUNGCAP NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	DIENTHOAI INT NULL,
	EMAIL NVARCHAR(50) NULL,
)
INSERT INTO [dbo].[NhaCungCap]([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[DIENTHOAI],[EMAIL])
VALUES ('NCC01',N'HonDa',N'799 Nguyễn Kiệm',0854926311,'Honda1234@gmail')

CREATE PROC select_NCC
as
	SELECT * FROM [dbo].[NhaCungCap]

EXEC select_NCC
CREATE TABLE PNhap
(
	MAPN NVARCHAR(50) NOT NULL
	CONSTRAINT pk_PNhap
	PRIMARY KEY(MAPN),
	MANHACUNGCAP NVARCHAR(50) NOT NULL,
	CONSTRAINT fk_PNhap_NhaCungCap
	FOREIGN KEY(MANHACUNGCAP)
	REFERENCES NhaCungCap(MANHACUNGCAP)
	ON DELETE CASCADE ON UPDATE CASCADE,
	MANHANVIEN NVARCHAR(50) NOT NULL
	CONSTRAINT fk_PNhap_NhanVien
	FOREIGN KEY(MANHANVIEN)
	REFERENCES NhanVien(MANHANVIEN)
	ON DELETE CASCADE ON UPDATE CASCADE,
	NGAYNHAP DATETIME NOT NULL,
)
CREATE TABLE CTPNhap
(
	MAPN NVARCHAR(50) NOT NULL,
	MALOAI NVARCHAR(20) NOT NULL,
	TENLOAI NVARCHAR(50) NOT NULL,
	SLNHAP INT NOT NULL,
	THUE FLOAT,
	DONGIANHAP FLOAT NOT NULL,
	CONSTRAINT pk_CTPNhap
	PRIMARY KEY(MAPN,MALOAI),
	CONSTRAINT fk_CTPNhap_XeMay
	FOREIGN KEY(MALOAI)
	REFERENCES LoaiXe(MALOAI)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_CTPNhap_PNhap
	FOREIGN KEY(MAPN)
	REFERENCES PNhap(MAPN)
	ON DELETE CASCADE ON UPDATE CASCADE
)
CREATE TABLE PXuat
(
	MAPX NVARCHAR(50) NOT NULL,
	CONSTRAINT pk_PXuat
	PRIMARY KEY(MAPX),
	NGAYXUAT DATETIME NOT NULL,
	MAKHACHHANG NVARCHAR(50) NOT NULL,
	CONSTRAINT fk_PXuat_KhachHang
	FOREIGN KEY(MAKHACHHANG)
	REFERENCES KhachHang(MAKHACHHANG)
	ON DELETE CASCADE ON UPDATE CASCADE,
	MANHANVIEN NVARCHAR(50) NOT NULL,
	CONSTRAINT fk_PXuat_NhanVien
	FOREIGN KEY(MANHANVIEN)
	REFERENCES NhanVien(MANHANVIEN)
	ON DELETE CASCADE ON UPDATE CASCADE
)
CREATE TABLE CTPXuat
(
	MAPX NVARCHAR(50) NOT NULL,
	MAXE NVARCHAR(50) NOT NULL,
	SLXUAT INT NOT NULL,
	THUE FLOAT,
	DONGIANHAP FLOAT NOT NULL,
	CONSTRAINT pk_CTPXuat
	PRIMARY KEY(MAPX,MAXE),
	CONSTRAINT fk_CTPXuat_XeMay
	FOREIGN KEY(MAXE)
	REFERENCES XeMay(MAXE)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_CTPXuat_PXuat
	FOREIGN KEY(MAPX)
	REFERENCES PXuat(MAPX)
	ON DELETE CASCADE ON UPDATE CASCADE
)
CREATE TABLE Login
(
	HO NVARCHAR(10) NOT NULL,
	TEN NVARCHAR(10) NOT NULL,
	TAIKHOAN NVARCHAR(30) NOT NULL,
	EMAIL NVARCHAR(40) NOT NULL,
	MATKHAU NVARCHAR(20) NOT NULL,
	GIOITINH NVARCHAR(10) NOT NULL
)
INSERT INTO [dbo].[Login]
VALUES(N'Nguyễn',N'Hùng','admin','hung@gmail','admin','Nam')

select * from [dbo].[Login] where [TAIKHOAN] = 'admin' and [MATKHAU] = 'admin'

SELECT * FROM [dbo].[KhachHang]
SELECT * FROM [dbo].[Login]

INSERT [dbo].[LoaiXe]
VALUES('LX01','SH','HonDa',10,150,130,80000000)
INSERT [dbo].[XeMay] 
VALUES('X01','LX01',123213,45435,N'Trắng',50000000)
CREATE TRIGGER trg_themXe ON [dbo].[XeMay]
FOR INSERT
AS
	UPDATE [dbo].[LoaiXe] 
	SET SOLUONG = SOLUONG + 1

CREATE TRIGGER trg_XoaXe ON [dbo].[XeMay]
FOR DELETE
AS
	UPDATE [dbo].[LoaiXe] 
	SET SOLUONG = SOLUONG - 1

SELECT * FROM [dbo].[LoaiXe]
SELECT * FROM [dbo].[XeMay]