//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.20 at 07:23:39 PM ICT 
//

package sesion11.dom.product;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the sesion11.dom.product package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Website_QNAME = new QName("", "website");
	private final static QName _Manufacture_QNAME = new QName("", "manufacture");
	private final static QName _Description_QNAME = new QName("", "description");
	private final static QName _Name_QNAME = new QName("", "name");
	private final static QName _Unitbaseprice_QNAME = new QName("",
			"unitbaseprice");
	private final static QName _Country_QNAME = new QName("", "country");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: sesion11.dom.product
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Productlist }
	 * 
	 */
	public Productlist createProductlist() {
		return new Productlist();
	}

	/**
	 * Create an instance of {@link Product }
	 * 
	 */
	public Product createProduct() {
		return new Product();
	}

	/**
	 * Create an instance of {@link Suplier }
	 * 
	 */
	public Suplier createSuplier() {
		return new Suplier();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "website")
	public JAXBElement<String> createWebsite(String value) {
		return new JAXBElement<String>(_Website_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "manufacture")
	public JAXBElement<String> createManufacture(String value) {
		return new JAXBElement<String>(_Manufacture_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "description")
	public JAXBElement<String> createDescription(String value) {
		return new JAXBElement<String>(_Description_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "name")
	public JAXBElement<String> createName(String value) {
		return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "unitbaseprice")
	public JAXBElement<Double> createUnitbaseprice(Double value) {
		return new JAXBElement<Double>(_Unitbaseprice_QNAME, Double.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "country")
	public JAXBElement<String> createCountry(String value) {
		return new JAXBElement<String>(_Country_QNAME, String.class, null,
				value);
	}

}
